import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "fw-bg-base": "var(--color-bg-base)",
        "fw-bg-surface": "var(--color-bg-surface)",
        "fw-bg-elevated": "var(--color-bg-elevated)",
        "fw-bg-subtle": "var(--color-bg-subtle)",
        "fw-accent": "var(--color-accent-primary)",
        "fw-accent-hover": "var(--color-accent-hover)",
        "fw-accent-muted": "var(--color-accent-muted)",
        "fw-danger": "var(--color-danger)",
        "fw-danger-muted": "var(--color-danger-muted)",
        "fw-warning": "var(--color-warning)",
        "fw-success": "var(--color-success)",
        "fw-text": "var(--color-text-primary)",
        "fw-text-secondary": "var(--color-text-secondary)",
        "fw-text-tertiary": "var(--color-text-tertiary)",
        "fw-text-inverse": "var(--color-text-inverse)",
        "fw-border": "var(--color-border-default)",
        "fw-border-strong": "var(--color-border-strong)",
        /* Legacy semantic names mapped to design tokens */
        "primary": "var(--color-bg-base)",
        "secondary-bg": "var(--color-bg-surface)",
        "dark-text": "var(--color-text-primary)",
        "muted": "var(--color-text-secondary)",
        "accent": "var(--color-accent-primary)",
        "accent-light": "var(--color-accent-hover)",
        "danger": "var(--color-danger)",
        "warning": "var(--color-warning)",
        "success": "var(--color-success)",
        "border": "var(--color-border-default)",
        "border-light": "var(--color-border-strong)",
        "trust-bg": "var(--color-bg-subtle)",
        "focus-ring": "var(--color-accent-muted)",
        "input-bg": "var(--color-bg-surface)",
        "hero-from": "var(--color-bg-base)",
      },
      fontFamily: {
        display: ["var(--font-display)", "Georgia", "serif"],
        sans: ["var(--font-body)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "monospace"],
        label: ["var(--font-label)", "sans-serif"],
      },
      fontSize: {
        "fw-xs": "var(--text-xs)",
        "fw-sm": "var(--text-sm)",
        "fw-base": "var(--text-base)",
        "fw-lg": "var(--text-lg)",
        "fw-xl": "var(--text-xl)",
        "fw-2xl": "var(--text-2xl)",
        "fw-3xl": "var(--text-3xl)",
        "fw-4xl": "var(--text-4xl)",
        "fw-5xl": "var(--text-5xl)",
        "fw-6xl": "var(--text-6xl)",
        "small": "var(--text-sm)",
        "body": "var(--text-base)",
        "subhead-mobile": "1rem",
        "subhead-desktop": "var(--text-xl)",
        "section-mobile": "var(--text-2xl)",
        "section-desktop": "var(--text-3xl)",
        "eyebrow": "var(--text-sm)",
      },
      spacing: {
        "fw-1": "var(--space-1)",
        "fw-2": "var(--space-2)",
        "fw-3": "var(--space-3)",
        "fw-4": "var(--space-4)",
        "fw-5": "var(--space-5)",
        "fw-6": "var(--space-6)",
        "fw-7": "var(--space-7)",
        "fw-8": "var(--space-8)",
        "fw-9": "var(--space-9)",
        "fw-10": "var(--space-10)",
        "section-y": "var(--space-9)",
        "section-y-mobile": "var(--space-7)",
        "section-trust": "var(--space-5)",
      },
      borderRadius: {
        "fw-sm": "var(--radius-sm)",
        "fw-md": "var(--radius-md)",
        "fw-lg": "var(--radius-lg)",
        "fw-xl": "var(--radius-xl)",
        "fw-full": "var(--radius-full)",
        "button": "var(--radius-full)",
        "card": "var(--radius-lg)",
        "dropzone": "var(--radius-xl)",
        "input": "var(--radius-md)",
      },
      boxShadow: {
        "fw-sm": "var(--shadow-sm)",
        "fw-md": "var(--shadow-md)",
        "fw-lg": "var(--shadow-lg)",
        "fw-teal": "none",
        "fw-danger": "none",
        "card": "0 1px 3px rgba(0,0,0,0.08)",
        "card-hover": "0 4px 12px rgba(0,0,0,0.06)",
        "button-accent": "0 4px 12px rgba(0,0,0,0.06)",
        "button-accent-hover": "0 4px 12px rgba(0,0,0,0.08)",
        "mockup": "0 4px 12px rgba(0,0,0,0.06)",
      },
      maxWidth: {
        "fw-content": "var(--max-width-content)",
        "fw-text": "var(--max-width-text)",
        "fw-narrow": "var(--max-width-narrow)",
      },
      transitionTimingFunction: {
        "fw-out": "var(--ease-out)",
        "fw-in": "var(--ease-in)",
        "fw-inout": "var(--ease-inout)",
      },
      transitionDuration: {
        "fw-fast": "var(--duration-fast)",
        "fw-base": "var(--duration-base)",
        "fw-slow": "var(--duration-slow)",
        "fw-slower": "var(--duration-slower)",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        bounceSoft: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(2px)" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 600ms var(--ease-out) forwards",
        "bounce-soft": "bounceSoft 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
